all:
	g++ receiver1.cpp -o receiver1
	g++ receiver2.cpp -o receiver2
	g++ receiver3.cpp -o receiver3
	g++ sender1.cpp -o sender1
	g++ sender2.cpp -o sender2
	g++ sender3.cpp -o sender3

clean:
	rm -rf *.o receiver1
	rm -rf *.o receiver2
	rm -rf *.o receiver3
	rm -rf *.o sender1
	rm -rf *.o sender2
	rm -rf *.o sender3
